#!/bin/bash
# Copyright (c) 2014 The Native Client Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is for bash on NaCl. Note that you cannot use external commands
# until the installation is completed. Also, you cannot use features
# which nacl_io does not support yet (e.g., pipes and sub-shells).

InstallPackage() {
  local package_name="$1.${2:-${NACL_ARCH}}"
  local archive=/mnt/http/tarballs/${package_name}.zip
  local stamp=stamp/${package_name}
  if [ ! -e /mnt/html5/mingn/${stamp} ]; then
    echo "Installing ${package_name} package..."
  else
    source /mnt/http/${stamp}
    source /mnt/html5/mingn/${stamp}
    if [ "${INSTALLED}" = "${LATEST}" ]; then
      # The archive is up to date.
      return
    fi
    echo "Updating ${package_name} package..."
  fi
  if [ ! -e ${archive} ]; then
    echo "${archive} does not exist!"
    return
  fi
  # -o: overwrite -q: quiet -d: destination
  unzip -oqd /mnt/html5 ${archive}
}

InstallPackage base
InstallPackage lib all

# Set up environment variables so that we can use installed binaries.
LIB_DIR=lib32
if [ ${NACL_ARCH} = "x86_64" ]; then
  LIB_DIR=lib
fi
export HOME=/mnt/html5
export NACL_SDK_ROOT=${HOME}/mingn
NACL_TOOLCHAIN_ROOT=${NACL_SDK_ROOT}/toolchain/nacl_x86_glibc
LD_LIBRARY_PATH=${NACL_TOOLCHAIN_ROOT}/x86_64-nacl/${LIB_DIR}
LD_LIBRARY_PATH+=:${NACL_TOOLCHAIN_ROOT}/${NACL_ARCH}-nacl/usr/lib
export LD_LIBRARY_PATH
export PATH=${NACL_SDK_ROOT}/toolchain/nacl_x86_glibc/bin

cd ${HOME}
if [ -e ${HOME}/.bashrc ]; then
  source ${HOME}/.bashrc
fi
