#!/bin/bash
# Copyright (c) 2011 The Native Client Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source pkg_info
source ../../build_tools/common.sh

MAKEFILE_PATCH_FILE=nacl-fontconfig.Makefile.patch

# fontconfig with-arch to be set for cross compiling
#export with_arch=i686


ExtractStep() {
  DefaultExtractStep

  ############################################################################
  # Recreation of configure/Makefile.in/config.sub/etc.
  # Will ask for autotools.
  ############################################################################
  ChangeDir ${NACL_PACKAGES_REPOSITORY}/${PACKAGE_NAME}
  if [ ! -f configure ]; then
    ./autogen.sh --with-arch=x86
    make distclean
    Banner "Build host configuration"

    MakeDir ${NACL_PACKAGES_REPOSITORY}/${PACKAGE_DIR}/build-nacl-host
    ChangeDir ${NACL_PACKAGES_REPOSITORY}/${PACKAGE_DIR}/build-nacl-host
    CFLAGS='' LDFLAGS='' LogExecute ../configure
    LogExecute make
  fi
}


PatchStep() {
  DefaultPatchStep
  chmod a+x ${NACL_PACKAGES_REPOSITORY}/${PACKAGE_NAME}/pseudo-gcc
}


ConfigureStep() {
  Banner "Configuring ${PACKAGE_NAME}"

  # We'll not build host anyway
  export CC_FOR_BUILD=${NACL_PACKAGES_REPOSITORY}/${PACKAGE_NAME}/pseudo-gcc
  EXTRA_CONFIGURE_ARGS="--disable-docs --with-arch=x86"

  # The configure script for fontconfig uses AC_PATH_PROG rather than
  # AC_PATH_TOOL when looking for freetype-config, so it doesn't finds the
  # system one rather than one in the toolchain.
  EXTRA_CONFIGURE_ARGS+=" --with-freetype-config=${NACLPORTS_PREFIX}/bin/freetype-config"
  DefaultConfigureStep

  # Use the autogenerated files from the host build
  LogExecute cp "../build-nacl-host/fc-case/fccase.h" "fc-case/fccase.h"
  LogExecute cp "../build-nacl-host/fc-lang/fclang.h" "fc-lang/fclang.h"
  LogExecute cp "../build-nacl-host/fc-glyphname/fcglyphname.h" "fc-glyphname/fcglyphname.h"
  LogExecute cp "../build-nacl-host/fc-arch/fcarch.h" "fc-arch/fcarch.h"
}


PatchMakefileStep() {
  # fontconfig wants to build executable tools.  These tools aren't needed
  # for Native Client.  This function will patch the generated Makefile
  # to remove them.  (Use fontconfig tools on your build machine instead.)
  Banner "PatchMakefileStep"
  ChangeDir ${NACL_PACKAGES_REPOSITORY}/${PACKAGE_NAME}/${NACL_BUILD_SUBDIR}
  patch -p1 -g0 --no-backup-if-mismatch < ${START_DIR}/${MAKEFILE_PATCH_FILE}
}


PackageInstall() {
  PreInstallStep
  DownloadStep
  ExtractStep
  PatchStep
  ConfigureStep
  PatchMakefileStep
  BuildStep
  InstallStep
}


PackageInstall
exit 0
